// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
// Placeholder data
const rubros = [
  { id: 'rubro1', descripcion: 'Rubro 1' },
  { id: 'rubro2', descripcion: 'Rubro 2' },
  { id: 'rubro3', descripcion: 'Rubro 3' },
  { id: 'rubro4', descripcion: 'Rubro 4' },
];

const productos = [
  {
    id: 'producto1',
    descripcion: 'Producto 1',
    rubroId: 'rubro1',
    valorVigente: 100.0,
  },
  {
    id: 'producto2',
    descripcion: 'Producto 2',
    rubroId: 'rubro2',
    valorVigente: 200.0,
  },
  {
    id: 'producto3',
    descripcion: 'Producto 3',
    rubroId: 'rubro3',
    valorVigente: 300.0,
  },
  {
    id: 'producto4',
    descripcion: 'Producto 4',
    rubroId: 'rubro4',
    valorVigente: 400.0,
  },
];

const productoCotizaciones = [
  { id: 'prodCot1', productoId: 'producto1', cantidad: 10, cotizacionId: 1 },
  { id: 'prodCot2', productoId: 'producto2', cantidad: 20, cotizacionId: 2 },
  { id: 'prodCot3', productoId: 'producto3', cantidad: 30, cotizacionId: 3 },
];

const proveedores = [
  {
    id: 'proveedor1',
    nombre: 'Proveedor 1',
    nit: '123',
    direccion: 'Calle 1',
    email: 'proveedor1@example.com',
    telefono: '1234567890',
  },
  {
    id: 'proveedor2',
    nombre: 'Proveedor 2',
    nit: '456',
    direccion: 'Calle 2',
    email: 'proveedor2@example.com',
    telefono: '0987654321',
  },
  {
    id: 'proveedor3',
    nombre: 'Proveedor 3',
    nit: '789',
    direccion: 'Calle 3',
    email: 'proveedor3@example.com',
    telefono: '1122334455',
  },
  {
    id: 'proveedor4',
    nombre: 'Proveedor 4',
    nit: '012',
    direccion: 'Calle 4',
    email: 'proveedor4@example.com',
    telefono: '5566778899',
  },
];

const productoProveedores = [
  {
    productoCotizacionId: 'prodCot1',
    proveedorId: 'proveedor1',
    valor: 100.0,
  },
  {
    productoCotizacionId: 'prodCot1',
    proveedorId: 'proveedor2',
    valor: 200.0,
  },
  {
    productoCotizacionId: 'prodCot2',
    proveedorId: 'proveedor3',
    valor: 300.0,
  },
  {
    productoCotizacionId: 'prodCot3',
    proveedorId: 'proveedor4',
    valor: 400.0,
  },
];

// Placeholder data
const entidades = [
  {
    id: 1,
    nombre: 'Entidad 1',
    nit: '123',
    direccion: 'Calle 1',
    telefono: '1234567890',
    municipio: 'Municipio 1',
    departamento: 'Departamento 1',
    pais: 'Pais 1',
    web: 'www.entidad1.com',
    email: 'entidad1@example.com',
    resolucionPosesion: 'Resolucion 1',
    fechaPosesion: new Date(),
    estado: 'Activo',
    saldoDisponible: 1000.0,
  },
  {
    id: 2,
    nombre: 'Entidad 2',
    nit: '456',
    direccion: 'Calle 2',
    telefono: '0987654321',
    municipio: 'Municipio 2',
    departamento: 'Departamento 2',
    pais: 'Pais 2',
    web: 'www.entidad2.com',
    email: 'entidad2@example.com',
    resolucionPosesion: 'Resolucion 2',
    fechaPosesion: new Date(),
    estado: 'Activo',
    saldoDisponible: 2000.0,
  },
  {
    id: 3,
    nombre: 'Entidad 3',
    nit: '789',
    direccion: 'Calle 3',
    telefono: '1122334455',
    municipio: 'Municipio 3',
    departamento: 'Departamento 3',
    pais: 'Pais 3',
    web: 'www.entidad3.com',
    email: 'entidad3@example.com',
    resolucionPosesion: 'Resolucion 3',
    fechaPosesion: new Date(),
    estado: 'Activo',
    saldoDisponible: 3000.0,
  },
];

const secciones = [
  {
    id: 1,
    nombre: 'Seccion 1',
    nit: '123',
    direccion: 'Calle 1',
    telefono: '1234567890',
    municipio: 'Municipio 1',
    departamento: 'Departamento 1',
    pais: 'Pais 1',
    web: 'www.seccion1.com',
    email: 'seccion1@example.com',
    resolucionPosesion: 'Resolucion 1',
    fechaPosesion: new Date(),
    estado: 'Activo',
    entidadId: 1,
    saldoDisponible: 1000.0,
    usuarioId: 'usuario1',
  },
  {
    id: 2,
    nombre: 'Seccion 2',
    nit: '456',
    direccion: 'Calle 2',
    telefono: '0987654321',
    municipio: 'Municipio 2',
    departamento: 'Departamento 2',
    pais: 'Pais 2',
    web: 'www.seccion2.com',
    email: 'seccion2@example.com',
    resolucionPosesion: 'Resolucion 2',
    fechaPosesion: new Date(),
    estado: 'Activo',
    entidadId: 2,
    saldoDisponible: 2000.0,
    usuarioId: 'usuario2',
  },
  {
    id: 3,
    nombre: 'Seccion 3',
    nit: '789',
    direccion: 'Calle 3',
    telefono: '1122334455',
    municipio: 'Municipio 3',
    departamento: 'Departamento 3',
    pais: 'Pais 3',
    web: 'www.seccion3.com',
    email: 'seccion3@example.com',
    resolucionPosesion: 'Resolucion 3',
    fechaPosesion: new Date(),
    estado: 'Activo',
    entidadId: 3,
    saldoDisponible: 3000.0,
    usuarioId: 'usuario3',
  },
];

const usuarios = [
  {
    id: 'usuario1',
    primerNombre: 'Usuario',
    segundoNombre: '1',
    primerApellido: 'Apellido',
    segundoApellido: '1',
    tipoDocumento: 'CC',
    documento: '123',
    telefono: '1234567890',
    celular: '0987654321',
    email: 'usuario1@example.com',
    direccion: 'Calle 1',
    estado: 'Activo',
    tipo: 'Administrador',
    password: 'admin123',
  },
  {
    id: 'usuario2',
    primerNombre: 'Usuario',
    segundoNombre: '2',
    primerApellido: 'Apellido',
    segundoApellido: '2',
    tipoDocumento: 'CC',
    documento: '456',
    telefono: '1122334455',
    celular: '5566778899',
    email: 'usuario2@example.com',
    direccion: 'Calle 2',
    estado: 'Activo',
    tipo: 'Encargado',
    password: 'admin1234',
  },
  {
    id: 'usuario3',
    primerNombre: 'Usuario',
    segundoNombre: '3',
    primerApellido: 'Apellido',
    segundoApellido: '3',
    tipoDocumento: 'CC',
    documento: '789',
    telefono: '1029384756',
    celular: '6574839201',
    email: 'usuario3@example.com',
    direccion: 'Calle 3',
    estado: 'Activo',
    tipo: 'Administrador',
    password: 'admin1235',
  },
];

const cicloContrataciones = [
  {
    id: 'ciclo1',
    fechaInicio: new Date(),
    fechaFinal: new Date(),
    usuarioId: 'usuario1',
    entidadId: 1,
  },
  {
    id: 'ciclo2',
    fechaInicio: new Date(),
    fechaFinal: new Date(),
    usuarioId: 'usuario2',
    entidadId: 2,
  },
  {
    id: 'ciclo3',
    fechaInicio: new Date(),
    fechaFinal: new Date(),
    usuarioId: 'usuario3',
    entidadId: 3,
  },
];

const cotizaciones = [
  {
    id: 1,
    fecha: new Date(),
    estado: 'Abierto',
    valorTotal: 1000.0,
    seccionId: 1,
    usuarioId: 'usuario1',
    cicloContratacionId: 'ciclo1',
  },
  {
    id: 2,
    fecha: new Date(),
    estado: 'EnProceso',
    valorTotal: 2000.0,
    seccionId: 2,
    usuarioId: 'usuario2',
    cicloContratacionId: 'ciclo2',
  },
  {
    id: 3,
    fecha: new Date(),
    estado: 'Cerrado',
    valorTotal: 3000.0,
    seccionId: 3,
    usuarioId: 'usuario3',
    cicloContratacionId: 'ciclo3',
  },
];

module.exports = {
  rubros,
  productos,
  proveedores,
  productoProveedores,
  entidades,
  secciones,
  usuarios,
  cicloContrataciones,
  cotizaciones,
  productoCotizaciones,
};
